import type { Metadata } from 'next'
import localFont from 'next/font/local'

import QueryClientProvider from '@/components/organisms/providers/react-query'

import './globals.css'

export const getSchwifty = localFont({
  src: '../../public/fonts/get_schwifty.ttf',
  variable: '--font-schwifty'
})

export const metadata: Metadata = {
  title: 'Rick and Morty Charater',
  description: 'Generated by rick and morty universe'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={` ${getSchwifty.variable} antialiased`}>
        <QueryClientProvider>
          <main className="flex min-h-screen w-full flex-col items-center justify-center overflow-hidden bg-[url('/bg-primary.webp')] bg-cover bg-center">
            {children}
          </main>
        </QueryClientProvider>
      </body>
    </html>
  )
}
